# Generated by Django 4.2.7 on 2025-11-09 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=200, unique=True)),
                ('importance_score', models.FloatField()),
                ('rank', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Importancia de Característica',
                'verbose_name_plural': 'Importancia de Características',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='MalwareAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('malware_type', models.CharField(choices=[('benign', 'Benigno'), ('adware', 'Adware'), ('malware', 'Malware General')], max_length=50)),
                ('confidence', models.FloatField(help_text='Confianza de la predicción')),
                ('f1_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Análisis de Malware',
                'verbose_name_plural': 'Análisis de Malware',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('decision_forest', 'Decision Forest'), ('random_forest_classification', 'Random Forest (Clasificación)'), ('random_forest_regression', 'Random Forest (Regresión)')], max_length=50)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('with_scaler', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Métrica del Modelo',
                'verbose_name_plural': 'Métricas del Modelo',
                'ordering': ['model_type', 'metric_name'],
            },
        ),
    ]
